### PR TITLE
fix: bind IAddressable instances to runtime when deserializing from JSON #10

### PR DESCRIPTION
**Pull request by heikki-heikkinen-ptcs**
Uses Orleans JSON serialization settings instead of copy-pasting the same code to this library. Orleans.Core was already referenced.
Extracts serialization to/from RedisValue behind an interface where the implementation is selected when bootstrapping.
Attempts to fix migration from old implementation where state was stored as a plain key without etag to hash based structure.
Adds extension point to inject custom JSON converters to the JSON serialization settings.

### CODE REVIEW

**Comment by heikki-heikkinen-ptcs** [comment]
The format selection in RedisGrainStorage.GetKey (`var format = _options.UseJson ? "json" : "binary";`) does not belong in that class any more, will fix on monday.

**Comment by heikki-heikkinen-ptcs** [comment]
What is wrong with the CI? The test stage takes hours and then gets canceled?

**Comment by ReubenBond** [comment]
I'm not sure @heikki-heikkinen-ptcs - does this work locally for you?

**Comment by ReubenBond** [comment]
By the way, have you seen https://github.com/dotnet/orleans/pull/6936?

**Comment by heikki-heikkinen-ptcs** [comment]
Yes, test pass locally. They are a bit heavy since they require an actual redis instance to be running. I would strongly recommend checking out the branch while reviewing and running it locally. You tend not to see enough of the context when only looking at the diff.

And no, I have not seen that. I'll have to check it out.

**Comment by ReubenBond** [comment]
Those CI tests run against a Redis container.

**Comment by heikki-heikkinen-ptcs** [comment]
@ReubenBond I removed the test class I added and tests seem to pass now.

**Comment by heikki-heikkinen-ptcs** [comment]
Resolved conflicts with target branch. Is this ever going to get reviewed?

**Comment by ReubenBond** [comment]
Many apologies, @heikki-heikkinen-ptcs, I completely missed this.

**Pull request merged**
